### ISSUE TITLE
OCR-Print Text-Display Text Overlay with Image

### ISSUE THREAD

**Issue by CCYChongyanChen** [Azure-Samples/cognitive-services-quickstart-code#243]
Hi there,
### Goal
I am trying to detect text in the image and locate where the text is.
### Issue
Current code to display the image and overlay it with the extracted text cannot handle the image with angles.
`plt.figure(figsize=(5, 5))
image = Image.open(BytesIO(requests.get(image_url).content))
ax = plt.imshow(image, alpha=0.5)
for word in word_infos:
    bbox = [int(num) for num in word["boundingBox"].split(",")]
    text = word["text"]
    origin = (bbox[0], bbox[1])
    patch = Rectangle(origin, bbox[2], bbox[3],
                      fill=False, linewidth=2, color='y')
    ax.axes.add_patch(patch)
    plt.text(origin[0], origin[1], text, fontsize=20, weight="bold", va="top")
plt.show()
plt.axis("off")`

### Example
The image example I use is:
"https://ivc.ischool.utexas.edu/VizWiz_visualization_img/VizWiz_train_00013129.jpg"

![image](https://user-images.githubusercontent.com/21120604/118452467-cda1ba80-b6bb-11eb-98a3-a7b0c0e56f81.png)

![image](https://user-images.githubusercontent.com/21120604/118452439-c5e21600-b6bb-11eb-9a90-5ee644ebdb40.png)

**Comment by fsharpn00b** [comment]
Hello @CCYChongyanChen,

First I humbly apologize for my very delayed reply to this issue.

From what I can tell, you are calling the method recognize_printed_text().

The methods recognize_printed_text() and recognize_printed_text_in_stream() are being deprecated in favor of read() and read_in_stream().

recognize_printed_text()/recognize_printed_text_in_stream() are able to detect the image orientation and correct it before processing. However, as you have seen, the bounding boxes for the words match the corrected image orientation instead of the original orientation. See also issue https://github.com/Azure-Samples/cognitive-services-quickstart-code/issues/260.

read() and read_in_stream() do not detect and correct the image orientation. However, they do return bounding boxes that match the image orientation even if it is not upright.

Here is sample code that draws bounding boxes over the first image you provided:

```

'''
Prerequisites
- requests
- azure.cognitiveservices.vision.computervision
- pillow
- matplotlib
'''

import requests, shutil, time
from azure.cognitiveservices.vision.computervision import ComputerVisionClient
from azure.cognitiveservices.vision.computervision.models import OperationStatusCodes
from msrest.authentication import CognitiveServicesCredentials
from PIL import Image
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Rectangle

'''
Authenticate Computer Vision client
'''
key = "PASTE_YOUR_COMPUTER_VISION_SUBSCRIPTION_KEY_HERE"
endpoint = "PASTE_YOUR_COMPUTER_VISION_ENDPOINT_HERE"

client = ComputerVisionClient(endpoint=endpoint, credentials=CognitiveServicesCredentials(key))

'''
Call API
'''	

# Download the remote image to a local file.
image_url = "https://ivc.ischool.utexas.edu/VizWiz_visualization_img/VizWiz_train_00013129.jpg"
response = requests.get(image_url, stream=True)
with open("1.jpg", "wb") as out_file:
    shutil.copyfileobj(response.raw, out_file)

image = Image.open("1.jpg")
# Optional: rotate the image to correct orientation.
#image = image.rotate(95)
image.save("2.jpg")

# Send the image file to the service.
with open("2.jpg", "rb") as f :
# Specify raw response to get the operation location.
	response = client.read_in_stream(f, raw=True)
read_operation_location = response.headers["Operation-Location"]
# Get the operation ID from the operation location URL.
operation_id = read_operation_location.split("/")[-1]
# Wait for the operation to finish.
while True:
    result = client.get_read_result(operation_id)
    if result.status not in ['notStarted', 'running']:
        break
    time.sleep(5)

if result.status != OperationStatusCodes.succeeded:
	print("Failed to read image. Result:")
	print(result)
	exit(1)

'''
Display the results
'''

plt.figure(figsize=(5, 5))
ax = plt.imshow(image, alpha=0.5)

for read_result in result.analyze_result.read_results:
	for line in read_result.lines:
		word_infos = line.words

		for word in word_infos:
			bb = word.bounding_box
# Bounding box has the format:
# [upper left x, upper left y, upper right x, upper right y, lower right x, lower right y, lower left x, lower left y]
			patch = Polygon([(bb[0], bb[1]), (bb[2], bb[3]), (bb[4], bb[5]), (bb[6], bb[7])], fill=False, linewidth=2, color='y')
			ax.axes.add_patch(patch)

plt.show()
plt.axis("off")
```

Please let me know if this addresses your issue. Again, my sincere apologies for the delayed reply.

**Comment by fsharpn00b** [comment]
Hello @CCYChongyanChen,

I am going to close this issue for now, but please feel free to reopen it if my previous reply did not address the issue.
Thank you!
