### ISSUE TITLE
Bad Class File ms-azure-cs-faceapi // Class file has wrong version 56 should be 52

### ISSUE THREAD

**Issue by brotenor** [Azure-Samples/cognitive-services-quickstart-code#269]
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Concern java/Face Api Vision Quickstart

I tried to follow the steps in your README
I create a folder with the FaceQuickstart.java + /lib with dependencies
+ms-azure-cs-faceapi.jar
+all sub dependenceies extract from the faceapi-dependencies.jar

I edit the authentificate part

        final String key = "e7caeff3-7d1c-41fd-a178-xxxxxxxxxxxx";
        final AzureRegions myRegion = AzureRegions.NORTHEUROPE;
        FaceAPI client = FaceAPIManager.authenticate(myRegion, key);

I change "REGION" by "myRegion" and "KEY" by "key" inside the "FaceAPI client" creation line

i try to run the command in console &/or autocompile with intelij and get the message of wrong version for the dependecy

(I tried for 2 days and cannont find any other guid neither doc on azure for java implementation, i'm not sur if i did the authentificate corretly (i created my account as student and i get the key + region name)

Sorry in advance if it is a shitty simple solution but cannot find on my own (i'm first year student-career reconversion)

>
### Any log messages given by the failure
Error Message in console :

    c:\DEV\PROJECT\MSPR4\QUICKSTART>javac FaceQuickstart.java -cp .;lib\*
    FaceQuickstart.java:115: error: cannot access FaceAPI
        public static List<UUID> detectFaces(FaceAPI client, String imageURL, String imageName) {
                                                                    ^
      bad class file: lib\ms-azure-cs-faceapi.jar(com/microsoft/azure/cognitiveservices/vision/faceapi/FaceAPI.class)
        class file has wrong version 56.0, should be 52.0
        Please remove or make sure it appears in the correct subdirectory of the classpath.

>
### Expected/desired behavior
working sample i guess.
>

### OS and Version?
> Windows 10 64 bits
### Versions
Java SDK 1.8.0_261
Intelij & Console
Donwloaded the dependencies from the jar in your repo
>

> ---------------------------------------------------------------
> Thanks in advance for your help

**Comment by fsharpn00b** [comment]
Hello @brotenor,

I am investigating this issue. Also, you probably noticed this already, but there was a bug in the quickstart.

```
final String key = "PASTE_YOUR_FACE_SUBSCRIPTION_KEY_HERE";

// Add your region of your Face subscription, for example 'westus', 'eastus', etc.
// List of Azure Regions: https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.faceapi.models.azureregions?view=azure-java-stable
final AzureRegions myRegion = AzureRegions.WESTUS;
```

should be:

```
final String KEY = "PASTE_YOUR_FACE_SUBSCRIPTION_KEY_HERE";

// Add your region of your Face subscription, for example 'westus', 'eastus', etc.
// List of Azure Regions: https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.faceapi.models.azureregions?view=azure-java-stable
final AzureRegions REGION = AzureRegions.WESTUS;
```

I just updated the quickstart to fix that.

Thank you,
fsharpn00b

**Comment by fsharpn00b** [comment]
I'm getting a somewhat similar error. I suspect this has to do with those .jar files in the samples repo being 2 years old. I am going to try to get an updated .jar file and see if that resolves this.

**Comment by brotenor** [comment]
Hello @fsharpn00b 
Thanks for the reply! I hope you can figure this out, your guides on this repo are just great thanks for your work!

**Comment by fsharpn00b** [comment]
Hello @brotenor, my pleasure and thank you for the kind words!

So, I searched for "class file has wrong version 56.0, should be 52.0".

The results I am seeing make me think that:
- The .jar files you downloaded from our samples repo were compiled with a later version of Java.
- Your IDE (IntelliJ) is compiling the quickstart code using an earlier version of Java.

As a result, Java is complaining about the version discrepancy.
Unfortunately I can't be more specific than that yet, because I've never seen this issue before and am not familiar with it.

Here's a list of SDK versions versus class versions.
https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers
You're apparently using Java 8 so that's why you see "52".
Those .jar files must have been compiled with Java 12 hence the "56".
To be honest I don't know enough about Java to know why we have these two different version numbers, or why your SDK version "1.8.0_261" equals Java 8.

As I understand it, the simpler fix would be to reconfigure your IDE to use a later version of Java (i.e. at least Java 12). I am not familiar with IntelliJ so I'm not sure how to do that yet.

You might find these questions/answers helpful:
https://stackoverflow.com/questions/28180915/class-file-has-wrong-version-52-0-should-be-50-0
https://stackoverflow.com/questions/29906659/java-compiling-error-in-command-prompt-class-file-has-wrong-version-52-0-shoul

The other alternative would be build the Azure SDK for Java with your existing compiler (Java 8), but that's hopefully something we can avoid.

I will try to narrow this down more - please let me know if you're able to make any progress with the above.

Thank you,
fsharpn00b

**Comment by brotenor** [comment]
Hi again @fsharpn00b

I feel dumb but it was indeed just a problem of my SDK beeing v8 instead of v12, i successfully compile it with SDK 12 with no problem and successfully connect to the api and run the default functions (get some error due to my limit of 20 call/min so its normal - free student licence)

I will try implement parts i need for my project and run test, thank you very much and sorry for the "noob" moove :)

Best Regards!

**Comment by fsharpn00b** [comment]
Hi @brotenor,

Great news that you were able to resolve the issue. I will close this for now but feel free to reopen if you run across other issues.

Thank you!
fsharpn00b

**Comment by brotenor** [comment]
Hello again @fsharpn00b,

I successfully recompiled the dependecy with my 1.8.291 java version and it works fine.

Right now i'm trying to convert the function using URL as detectWithUrl into STREAM as detectWithStream because i want to upload a file from my local computer (no web site for my project so i can't use URL and try to push a local img) and i encounter some difficulties to convert everything with byte[] instead of String URL.

Do you by any chance have example of STREAM BYTE[] instead of URL for JAVA? Quite the same question as the last person with python in issue. Do i reopen an issue?

Thanks in advance
