### ISSUE TITLE
ComputerVision Read API Call Produces Failure in Python

### ISSUE THREAD

**Issue by wayfarer1549** [Azure-Samples/cognitive-services-quickstart-code#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run python ComputerVisionQuickstart.py

### Any log messages given by the failure
>Traceback (most recent call last):
  File "ComputerVisionQuickstart.py", line 514, in <module>
    client_response = computervision_client.batch_read_file(remote_image_url, text_recognition_mode, raw=True)
  File "/Users/philipsj16/anaconda3/envs/msazure/lib/python3.7/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py", line 871, in batch_read_file
    header_parameters.update(custom_headers)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### Expected/desired behavior
> Completing the tutorial at: https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/python-sdk

### OS and Version?
> macOS (Mojave)

### Versions
> 10.14.6; Python 3.7.4

### Mention any other details that might be useful

> I believe the issue is the call to batch_read_file() is not correctly passing 'text_recognition' mode. It should be passed in kwargs instead.
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Thanks for the feedback, we added a fix for the batch_read_file(). The constructor changed with the new Computer Vision SDK update. Instead of taking in a TextRecognition Mode it only needs (if no options) the handwriting sample itself. Like this:
`computervision_client.batch_read_file_in_stream(local_image_handwritten, raw=True)`
In our example we included a parameter to retrieve the raw response as well, but this is optional.
This issue has been resolved, thanks.
