### ISSUE TITLE
UnsupportedMediaType issue

### ISSUE THREAD

**Issue by likwidgames** [Azure-Samples/cognitive-services-quickstart-code#48]
Attempting to send a .PDF file through Postman, which is resulting in the following error:

> "{\"value\":{\"error\":{\"code\":\"UnsupportedMediaType\",\"message\":\"In case of HTML form data, the multipart request must contain a document with a media type of - 'application/pdf', 'image/jpeg' or 'image/png'.\"}},\"formatters\":[],\"contentTypes\":[],\"statusCode\":415}"

When I output the ContentType of the file, it's "application/pdf".

```
private async Task AnalyzePdfForm(
            IFormRecognizerClient formClient, Guid modelId, IFormFile pdfFormFile)
        {
            if (pdfFormFile == null)
            {
                throw new Exception("Invalid PDF file");
            }
            Console.WriteLine(pdfFormFile.ContentType);
            try
            {
                using (Stream stream = pdfFormFile.OpenReadStream())
                {
                    AnalyzeResult result = await formClient.AnalyzeWithCustomModelAsync(modelId, stream, contentType: "application/pdf");
                   Console.WriteLine("\nExtracted data from:" + pdfFormFile);
                    DisplayAnalyzeResult(result);
                }
            }
            catch (ErrorResponseException e)
            {
                Console.WriteLine("Analyze PDF form : " + e.Message);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Analyze PDF form : " + ex.Message);
            }
        }
```

**Comment by wiazur** [comment]
@v-jaswel this is a Form Recognizer issue, can you take a look? Thanks.

**Comment by shashisadasivan** [comment]
I need to use a memoryStream in a project (dont have access to the fileSystem, so no FileStream) and i found out sending a memoryStrem causes the same issue.
Replicatable by replacing the code in AnalyzePdfForm() to:
```csharp
using (FileStream stream = new FileStream(pdfFormFile, FileMode.Open))
{
	//--> New code
	using(var memStream = new MemoryStream())
	{
		stream.CopyTo(memStream);
		stream.Position = 0;
		memStream.Position = 0;
		AnalyzeResult result = await formClient.AnalyzeWithCustomModelAsync(modelId, memStream, contentType: "application/pdf");

		Console.WriteLine("\nExtracted data from:" + pdfFormFile);
		DisplayAnalyzeResult(result);
	}
	//<-- New code
	//--> original code
	/*
	AnalyzeResult result = await formClient.AnalyzeWithCustomModelAsync(modelId, stream, contentType: "application/pdf");

	Console.WriteLine("\nExtracted data from:" + pdfFormFile);
	DisplayAnalyzeResult(result);
	*/
	//<-- original code
}
```

**Comment by v-jaswel** [comment]
@shashisadasivan Hello. I am able to reproduce your issue. If I send a MemoryStream instead of a FileStream, I get a 400 Bad Request response from the server. I have been stepping through the Form Recognizer SDK in the debugger. I suspect this is the culprit:

https://github.com/Azure/azure-sdk-for-net/blob/2da59be4b9f8f44843331e6500669a4d8fff56f6/sdk/cognitiveservices/FormRecognizer/src/Customizations/FormRecognizerClient2.cs#L104
```
FileStream _formStreamAsFileStream = formStream as FileStream;
if (_formStreamAsFileStream != null)
{
	_formStream.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
	{
		Name = "form_stream",
		FileName = _formStreamAsFileStream.Name
	};
	_formStream.Headers.Add("Content-Type", contentType);
}
```

It's trying to cast the stream to a FileStream. If you send a FileStream, the cast succeeds. If you send a MemoryStream, the cast fails. If the cast fails, the Content-Disposition and Content-Type headers are not set. I suspect that is why the request fails.
I will ask the product team if they can address this.

I will investigate the issue likwidgames is seeing also.

**Comment by v-jaswel** [comment]
@likwidgames Hello, first I humbly apologize for my very delayed reply.
I was able to reproduce the error you were seeing in Postman. I am now able to send the request successfully. I believe the issue was that I had not attached the .pdf to the request correctly.

In Postman, I did the following to send the request successfully.
1. Set the method to POST.
1. Set the URL to https://&lt;INSERT YOUR RESOURCE NAME&gt;.cognitiveservices.azure.com/formrecognizer/v1.0-preview/custom/models/&lt;INSERT YOUR MODEL ID&gt;/analyze
1. In the Headers tab, add key `Ocp-Apim-Subscription-Key` with value &lt;YOUR FORM RECOGNIZER SUBSCRIPTION KEY&gt;
1. In the Body tab:
    1. Set the radio button to form-data.
    1. Add key `form_stream`. Make sure the type is set to `File` and not `Text`. The type is a drop down that appears at the right side of the key field. I had to set the type before entering the name (form_stream). For additional information see: https://stackoverflow.com/a/39037889
    1. Once you set the `form_stream` key type to `File`, in the value column a button labeled "Select Files" appears. Click that and browse to your PDF file.

After doing that, I received a 200 response from the server.
Note I did not have to set the Content-Type header on the request.

If that does not work, please let me know and I can append my exported Postman request.
